### PR TITLE
feat(matcher): add toBeAccessible matcher

### LINKED ISSUE #104: Feature: toBeAccessible()
Would it be possible to create a Jest matcher so checks could read:

`expect(() => AccessibilityEngine.check(<Comp/>)).toBeAccessible()`

### PR DESCRIPTION
**Pull request by pke**
So what do you think @aryella-lacerda? Does this look good? Then I'll add README changes and create a real PR.

Closes #104

### CODE REVIEW

**Comment by aryella-lacerda** [comment]
Thanks for the PR! Looks great 👍🏼 😁

**Comment by pke** [comment]
I’ve converted this to a full PR then.
Happy to be able to remove my custom code from my projects once this has been merged.

**Comment by pke** [comment]
Ah readme update is missing.

**Comment by aryella-lacerda** [comment]
If I'm not mistaken, part of the installation process now is importing `react-native-accessibility-engine/src/extend-expect` inside the user's Jest setup file or directly in Jest's `setupFilesAfterEnv` array, correct? 🤔 We'd need to add that to the README too.

**Comment by pke** [comment]
That’s true. There is no automatic discovery of such extensions via package moniker or so, as far as I’m aware.

**Comment by pke** [comment]
@aryella-lacerda whats the correct path though? The package does not have a src folder, it has a dist folder if I am not mistaken?

**Comment by aryella-lacerda** [comment]
@pke The `src` folder does get distributed with the package. If you install it and open up the `react-native-accessibility-engine` folder inside `node_modules`, you'll see this (tested on v0.6.0):

Screen Shot 2021-11-04 at 8 01 50 AM

This behavior is defined by including `src` in the `files` array in package.json. So I think it's safe to use this path here:
`react-native-accessibility-engine/src/extend-expect`. We could try it out locally using npm link, and if that doesn't work, we could fall back to `react-native-accessibility-engine/lib/commonjs/extend-expect`. 🤔

**Comment by pke** [comment]
@aryella-lacerda added a readme entry. However I am not sure this will work with non-ts projects. We will see.

**Review by aryella-lacerda — APPROVED** [review]

**Comment by aryella-lacerda** [comment]
@pke I'm gonna merge this PR and test it out on a JS project today. I'll let you know the result. :v:

**Comment by pke** [comment]
Did it work? @aryella-lacerda

**Comment by aryella-lacerda** [comment]
@pke No, it worked only on Typescript projects and even in those, the Jest matcher type wasn't recognized by the client app.

#148 fixes the type errors by exposing the entire `types` folder from `index`. The client app should be able to recognize the .toBeAccessible() matcher with no configuration now. This fix was released in v1.7.2.

#151 updates the README to instruct the user to import the extend-expect file from `lib/commonjs` instead of `src`. So it should work in both JS and TS projects now.

**Comment by pke** [comment]
Cool. Thanks for the fixes.

**Pull request merged**
