### PR TITLE
bug: fixing the path to the typing files

### PR DESCRIPTION
**Pull request by davidx-roam**
There are no `src` inside the `typescript` folder

### CODE REVIEW

**Review by aryella-lacerda — APPROVED** [review]
Awesome, thank you for contributing! 👏👏👏

**Comment by davidx-roam** [comment]
> Awesome, thank you for contributing! 👏👏👏

Not a problem. Love your work :)

**Comment by davidx-roam** [comment]
@aryella-lacerda Hello, hello, it seems like there was a problem with releasing this change onto npm. When you have time, could you take a look please? Seems like something to do with SSH :/

**Comment by aryella-lacerda** [comment]
Hey @davidx-roam! Yeah, it's on the to-do list to fix the CI workflow but I haven't had the time to get to it. 😞  For now, I'm running the release script locally. Version 0.3.3 was just released. 👏🏼 Let me know if you have any problems with it.

**Pull request merged**
