### PR TITLE
feat: enable configurable options for toBeAccessible

### PR DESCRIPTION
**Pull request by emilyseibert**
This is the solution for the proposal described in this issue: https://github.com/aryella-lacerda/react-native-accessibility-engine/issues/310

### CODE REVIEW

**Review by aryella-lacerda — DISMISSED** [review]
This looks good 👍🏼 Thanks for contributing!

**Comment by emilyseibert** [comment]
@aryella-lacerda I believe I've fixed it in my latest commit. I removed the dead code, since TS enforces rule ids via types there'd be no 'undefined' rule. I'm not sure how to retrigger Codecov to confirm it passes. The PR is up to date with `main`.

**Review by aryella-lacerda — APPROVED** [review]

**Comment by aryella-lacerda** [comment]
Just released version `v3.2.0`! I noticed you added a `Breaking Change` warning to one of the commits, but I don't believe any of these adjustments are really breaking changes. 🤔 We can pass options to the matcher now but the lib won't break for users who don't.

**Comment by emilyseibert** [comment]
I don't see which commit you're referring to. I marked a few as 'feat' since it's a new capability, but I agree that nothing is breaking. Thanks for releasing!

**Pull request merged**
